# Generated by Django 3.2.5 on 2021-07-21 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StatusKostModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nik', models.CharField(max_length=50)),
                ('Status_kost', models.CharField(max_length=50)),
                ('Waktu_in', models.DateField()),
                ('Waktu_out', models.DateField()),
                ('no_kamar', models.IntegerField()),
            ],
        ),
    ]
