# Generated by Django 3.2.5 on 2021-07-21 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dash_admin', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='KamarKostModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nik', models.CharField(max_length=50)),
                ('No_kamar', models.IntegerField()),
                ('Waktu_in', models.DateField()),
                ('Waktu_out', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='PemasukanKostModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nik', models.CharField(max_length=50)),
                ('Tgl_pemasukan', models.DateField()),
                ('Jmlh_pemasukan', models.IntegerField()),
                ('Keterangan', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='PengeluaranKostModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Pengeluaran', models.CharField(max_length=50)),
                ('Tgl_pengeluaran', models.DateField()),
                ('jmlh_pengeluaran', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='StatusKostModel',
        ),
    ]
