# Generated by Django 3.2.5 on 2021-08-02 23:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dash_admin', '0003_alter_pemasukankostmodel_tgl_pemasukan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pemasukankostmodel',
            name='Tgl_pemasukan',
            field=models.DateField(default=datetime.datetime.now),
        ),
    ]
