# Generated by Django 3.2.7 on 2021-09-10 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dash_admin', '0004_alter_pemasukankostmodel_tgl_pemasukan'),
    ]

    operations = [
        migrations.AddField(
            model_name='kamarkostmodel',
            name='Relay',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
