# Generated by Django 3.2.7 on 2021-09-12 00:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dash_admin', '0005_kamarkostmodel_relay'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kamarkostmodel',
            name='Relay',
        ),
    ]
