# Generated by Django 3.2.7 on 2021-12-23 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dash_admin', '0006_remove_kamarkostmodel_relay'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kamarkostmodel',
            name='Nik',
            field=models.CharField(max_length=16),
        ),
        migrations.AlterField(
            model_name='pemasukankostmodel',
            name='Nik',
            field=models.CharField(max_length=16),
        ),
        migrations.AlterField(
            model_name='pengeluarankostmodel',
            name='Pengeluaran',
            field=models.CharField(max_length=150),
        ),
    ]
