# Generated by Django 3.2.5 on 2021-07-20 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RegisterTamuModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nik', models.CharField(max_length=50)),
                ('Nama_lengkap', models.CharField(max_length=50)),
                ('No_tlp', models.BigIntegerField()),
                ('Email', models.CharField(max_length=255)),
                ('Tempat_lahir', models.CharField(max_length=50)),
                ('Tanggal_lahir', models.DateField()),
                ('Agama', models.CharField(max_length=50)),
                ('Pekerjaan', models.CharField(max_length=50)),
                ('Jenis_kelamin', models.CharField(max_length=50)),
                ('Alamat_asal', models.CharField(max_length=255)),
                ('Foto_ktp', models.ImageField(upload_to='static/Foto_KTP')),
                ('published', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
