# Generated by Django 3.2.5 on 2021-07-21 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dash_tamu', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaketKostModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nik', models.CharField(max_length=50)),
                ('Paket', models.CharField(max_length=50)),
            ],
        ),
    ]
