# Generated by Django 3.2.5 on 2021-07-23 09:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dash_tamu', '0003_kritiksaranmodel'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='RegisterTamuModel',
            new_name='ProfilTamuModel',
        ),
    ]
