# Generated by Django 3.2.7 on 2021-12-13 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dash_tamu', '0004_rename_registertamumodel_profiltamumodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profiltamumodel',
            name='Foto_ktp',
            field=models.ImageField(upload_to='foto_ktp'),
        ),
    ]
