# Generated by Django 3.2.7 on 2021-12-23 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dash_tamu', '0005_alter_profiltamumodel_foto_ktp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profiltamumodel',
            name='Nik',
            field=models.CharField(max_length=16),
        ),
        migrations.AlterField(
            model_name='profiltamumodel',
            name='No_tlp',
            field=models.IntegerField(),
        ),
    ]
