# Generated by Django 3.2.7 on 2021-12-23 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dash_tamu', '0006_auto_20211223_1428'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profiltamumodel',
            name='No_tlp',
            field=models.CharField(max_length=12),
        ),
    ]
