# Generated by Django 3.2.7 on 2021-12-23 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dash_tamu', '0007_alter_profiltamumodel_no_tlp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kritiksaranmodel',
            name='Nik',
            field=models.CharField(max_length=16),
        ),
        migrations.AlterField(
            model_name='paketkostmodel',
            name='Nik',
            field=models.CharField(max_length=16),
        ),
    ]
